import {
  House,
  BookOpen,
  FolderOpen,
  PanelsTopLeft,
  CircleHelp,
  FileText,
  BarChart3,
  Sparkles,
  Library,
  ListChecks,
  User,
  Users,
  ScrollText,
  Settings2,
} from 'lucide-react';

export const NAV_ITEMS = [
  {
    label: 'Overview',
    key: 'dashboard',
    icon: House,
    to: '/dashboard',
    group: 'home',
    description: 'Your workspace at a glance',
    prefetch: ['/dashboard'],
  },
  {
    label: 'Subjects',
    key: 'subjects',
    icon: BookOpen,
    to: '/subjects',
    group: 'Workspace',
    description: 'Organize the courses you teach',
    prefetch: ['/subjects'],
  },
  {
    label: 'Materials',
    key: 'materials',
    icon: FolderOpen,
    to: '/materials',
    group: 'Workspace',
    description: 'Syllabi, lecture notes, and references',
    prefetch: ['/materials', '/subjects'],
  },
  {
    label: 'Blueprints',
    key: 'tos',
    icon: PanelsTopLeft,
    to: '/tos',
    group: 'Workspace',
    description: 'Plan your topic and Bloom coverage',
    prefetch: ['/tos', '/subjects'],
  },
  {
    label: 'Question bank',
    key: 'questions',
    icon: CircleHelp,
    to: '/questions',
    group: 'Assessment',
    description: 'Manage your private questions',
    prefetch: ['/questions?', '/subjects', '/tos'],
  },
  {
    label: 'Review drafts',
    key: 'review',
    icon: ListChecks,
    to: '/questions/review',
    group: 'Assessment',
    description: 'Check evidence and approve questions',
  },
  {
    label: 'Exams',
    key: 'exams',
    icon: FileText,
    to: '/exams',
    group: 'Assessment',
    description: 'Assemble, publish, and export exam sets',
    prefetch: ['/exams'],
  },
  {
    label: 'Results & insights',
    key: 'analytics',
    icon: BarChart3,
    to: '/analytics',
    group: 'Assessment',
    description: 'Explore exam results and item analysis',
    prefetch: ['/analytics/overview'],
  },
  {
    label: 'Shared bank',
    key: 'institution',
    icon: Library,
    to: '/questions/institution',
    group: 'Institution',
    description: 'Discover approved questions to reuse',
    prefetch: ['/questions/institution', '/subjects'],
  },
];

/** Superadmin console — replaces the instructor nav inside the same shell. */
export const ADMIN_NAV_ITEMS = [
  {
    label: 'Dashboard',
    key: 'dashboard',
    icon: House,
    to: '/admin/dashboard',
    group: 'home',
    description: 'Console overview and activity',
    prefetch: ['/admin/stats'],
  },
  {
    label: 'Users',
    key: 'users',
    icon: Users,
    to: '/admin/users',
    group: 'Manage',
    description: 'Approve and manage instructor accounts',
  },
  {
    label: 'Login logs',
    key: 'logins',
    icon: ScrollText,
    to: '/admin/logins',
    group: 'Security',
    description: 'Sign-in attempts with IP and user agent',
  },
  {
    label: 'Audit trail',
    key: 'audit',
    icon: ListChecks,
    to: '/admin/audit',
    group: 'Security',
    description: 'Recorded superadmin actions',
  },
  {
    label: 'Settings',
    key: 'settings',
    icon: Settings2,
    to: '/admin/settings',
    group: 'Security',
    description: 'reCAPTCHA and AI credentials',
  },
];

export const BUILD_ACTION = {
  label: 'Build an exam',
  key: 'wizard',
  icon: Sparkles,
  to: '/wizard',
  description: 'A guided path from materials to exam sets',
  prefetch: ['/subjects'],
};
export const COMMAND_ITEMS = [
  BUILD_ACTION,
  ...NAV_ITEMS,
  {
    label: 'Account settings',
    key: 'account',
    icon: User,
    to: '/account',
    description: 'Manage your instructor profile',
  },
];
